version: '3.9'
services:
  app:
    image: ghcr.io/algostract/portfolio-shirsendu:latest
    env_file:
      - .env
    volumes:
      - portfolio-shirsendu_static:/app/static
      - portfolio-shirsendu_data:/app/.data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  portfolio-shirsendu_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-shirsendu/static
  portfolio-shirsendu_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-shirsendu/.data

networks:
  internal:
    driver: overlay
